LOOMO:
  DOWNSCALE: 4
  IP: 128.179.157.205
  RECORDING: ../Results/loomostark.avi
PERCEPTION:
  BBOX_FACTOR: 1
  BENCHMARK_FILE: ../Benchmark/Woman
  GROUNDTRUTH: ../Benchmark/Woman/groundtruth_rect.txt
  PIFPAF_UPDATE_FREQUENCY: 10
  REINIT_WITH_PIFPAF_AFTER_TIMES: 40
  USE_PIFPAF_UPDATE: false
  VERBOSE: false
RECORDING:
  EXPID: 3
  FOLDER_FOR_PREDICTION: ../Results/OTB100/stark
  REPORT_ELPASED_TIME_FOLDER: ../Results/OTB100/stark
  SAVE_RESULTS: true
