PERCEPTION:
  VERBOSE: False
  BENCHMARK_FILE: "../data/loomo/loomobenchmark2/Loomo1.avi" #starting at python/  "../Benchmark/Loomo/Demo3/theo_Indoor.avi"
  BBOX_FACTOR: 1
  REINIT_WITH_PIFPAF_AFTER_TIMES:  40
  USE_PIFPAF_UPDATE: false
  PIFPAF_UPDATE_FREQUENCY: 10
  
LOOMO:
  IP: 128.179.184.252
  DOWNSCALE: 4
  RECORDING: "../Results/test.avi"
  
RECORDING:
  SAVE_RESULTS: True
  EXPID: 1
  FOLDER_FOR_PREDICTION: "../Results"
  REPORT_ELPASED_TIME_FOLDER: None #"../Results"
