LOOMO:
  DOWNSCALE: 4
  IP: 128.179.157.205
  RECORDING: ../Results/loomostark.avi
PERCEPTION:
  BBOX_FACTOR: 1
  BENCHMARK_FILE: ../Benchmark/Basketball
  GROUNDTRUTH: 
  PIFPAF_UPDATE_FREQUENCY: 10
  REINIT_WITH_PIFPAF_AFTER_TIMES: 40
  USE_PIFPAF_UPDATE: false
  VERBOSE: false
RECORDING:
  EXPID: 1
  FOLDER_FOR_PREDICTION: ../Results
  REPORT_ELPASED_TIME_FOLDER: #../Results/lasot/siam
  PATH_VIDEO_BBOX: ../Results/basketball.avi
  SAVE_RESULTS: true
