LOOMO:
  DOWNSCALE: 4
  IP: 128.179.184.252
  RECORDING: ../Results/test.avi
PERCEPTION:
  BBOX_FACTOR: 1
  BENCHMARK_FILE: ../Benchmark/LoomoBenchmark2/Loomo6.avi
  PIFPAF_UPDATE_FREQUENCY: 10
  REINIT_WITH_PIFPAF_AFTER_TIMES: 40
  USE_PIFPAF_UPDATE: false
  VERBOSE: false
RECORDING:
  EXPID: 6
  FOLDER_FOR_PREDICTION: ../Results/stark
  REPORT_ELPASED_TIME_FOLDER: ../Results/stark
  SAVE_RESULTS: true
