PERCEPTION:
  EXPID: 7
  SAVE_RESULTS: false
  VERBOSE: False
  IP: 128.179.158.94
  DOWNSCALE: 2
  BBOX_FACTOR: 0.7
  REINIT_WITH_PIFPAF_AFTER_TIMES: 10
  RECORDING: "../../Results/ID_0007_d2.avi"
  USE_PIFPAF_UPDATE: false
  PIFPAF_UPDATE_FREQUENCY: 10
  FOLDER_FOR_PREDICTION: "../../Results"
  BENCHMARK_FILE: "../Benchmark/Loomo/Demo3/theo_Indoor.avi" #starting at python/
  REPORT_ELPASED_TIME_FOLDER: "../../Results"
